# Languages supported by Argos Translate
# Source: https://github.com/argosopentech/argos-translate/blob/master/argostranslate/languages.csv

# Language code to language name mapping
# Language names are in their native language.
# e.g., "Deutsch" instead of "German", "Español" instead of "Spanish"
# This helps users identify their language more easily and prevents accidental
# translation of language names.  
# The list includes the top 10 most spoken languages globally for broader coverage.

language_map = {
    # Top 10 most spoken languages in the world
    'en': "English",
    'zh': "中文",
    'hi': "हिन्दी",
    'es': "Español",
    'fr': "Français",
    'ar': "العربية",
    'bn': "বাংলা",
    'ru': "Русский",
    'pt': "Português",
    'ur': "اردو",
    
    # Other languages supported by Argos Translate
    'aa': "Afaraf",
    'af': "Afrikaans",
    'ak': "Akan",
    'sq': "Shqip",
    'am': "አማርኛ",
    'an': "Aragonés",
    'hy': "Հայերեն",
    'as': "অসমীয়া",
    'av': "авар",
    'ae': "avesta",
    'ay': "Aymar",
    'az': "Azərbaycanca",
    'bm': "Bamanankan",
    'ba': "башҡорт",
    'eu': "Euskara",
    'be': "беларуская",
    'bh': "भोजपुरी",
    'bi': "Bislama",
    'bs': "bosanski",
    'br': "Brezhoneg",
    'bg': "български",
    'my': "ဗမာ",
    'ca': "català",
    'ch': "Chamoru",
    'ce': "нохчийн",
    'ny': "ChiCheŵa",
    'cv': "чӑваш",
    'kw': "Kernewek",
    'co': "Corsu",
    'cr': "ᓀᐦᐃᔭᐍᐏᐣ",
    'hr': "hrvatski",
    'cs': "čeština",
    'da': "dansk",
    'dv': "ދިވެހި",
    'nl': "Nederlands",
    'dz': "རྫོང་ཁ",
    'eo': "Esperanto",
    'et': "eesti",
    'ee': "Eʋegbe",
    'fo': "føroyskt",
    'fj': "Vakaviti",
    'fi': "suomi",
    'ff': "Fulfulde",
    'gl': "galego",
    'ka': "ქართული",
    'de': "Deutsch",
    'el': "ελληνικά",
    'gn': "Avañe'ẽ",
    'gu': "ગુજરાતી",
    'ht': "Kreyòl",
    'ha': "Hausa",
    'he': "עברית",
    'hz': "Otjiherero",
    'ho': "Hiri Motu",
    'hu': "magyar",
    'ia': "Interlingua",
    'id': "indonesia",
    'ie': "Interlingue",
    'ga': "Gaeilge",
    'ig': "Igbo",
    'ik': "Iñupiaq",
    'io': "Ido",
    'is': "Íslenska",
    'it': "italiano",
    'iu': "ᐃᓄᒃᑎᑐᑦ",
    'ja': "日本語",
    'jv': "Jawa",
    'kl': "kalaallisut",
    'kn': "ಕನ್ನಡ",
    'kr': "Kanuri",
    'ks': "कश्मीरी",
    'kk': "қазақ",
    'km': "ខ្មែរ",
    'ki': "Gĩkũyũ",
    'rw': "Ikinyarwanda",
    'ky': "кыргызча",
    'kv': "коми",
    'kg': "Kikongo",
    'ko': "한국어",
    'ku': "Kurdî",
    'kj': "Kuanyama",
    'la': "latine",
    'lb': "Lëtzebuergesch",
    'lg': "Luganda",
    'li': "Limburgs",
    'ln': "Lingála",
    'lo': "ລາວ",
    'lt': "lietuvių",
    'lu': "Kiluba",
    'lv': "latviešu",
    'gv': "Gaelg",
    'mk': "македонски",
    'mg': "malagasy",
    'ms': "melayu",
    'ml': "മലയാളം",
    'mt': "Malti",
    'mi': "Māori",
    'mr': "मराठी",
    'mh': "M̧ajeļ",
    'mn': "монгол",
    'na': "Dorerin Naoero",
    'nv': "Diné",
    'nd': "isiNdebele",
    'ne': "नेपाली",
    'ng': "Oshiwambo",
    'nb': "Bokmål",
    'nn': "Nynorsk",
    'no': "Norsk",
    'ii': "ꆈꌠ꒿",
    'nr': "isiNdebele",
    'oc': "occitan",
    'oj': "ᐊᓂᔑᓈᐯᒧᐎᓐ",
    'cu': "словѣньскъ",
    'om': "Oromoo",
    'or': "ଓଡ଼ିଆ",
    'os': "ирон",
    'pa': "ਪੰਜਾਬੀ",
    'pi': "पालि",
    'fa': "فارسی",
    'pl': "Polski",
    'ps': "پښتو",
    'qu': "Runa Simi",
    'rm': "Rumantsch",
    'rn': "Ikirundi",
    'ro': "Română",
    'sa': "संस्कृतम्",
    'sc': "Sardu",
    'sd': "सिन्धी",
    'se': "Davvisámegiella",
    'sm': "samoa",
    'sg': "Sängö",
    'sr': "српски",
    'gd': "Gàidhlig",
    'sn': "ChiShona",
    'si': "සිංහල",
    'sk': "Slovenčina",
    'sl': "Slovenščina",
    'so': "Soomaali",
    'st': "Sesotho",
    'su': "Sunda",
    'sw': "Kiswahili",
    'ss': "SiSwati",
    'sv': "svenska",
    'ta': "தமிழ்",
    'te': "తెలుగు",
    'tg': "тоҷикӣ",
    'th': "ไทย",
    'ti': "ትግርኛ",
    'bo': "བོད་ཡིག",
    'tk': "Türkmen",
    'tl': "Tagalog",
    'tn': "Setswana",
    'to': "Tonga",
    'tr': "Türkçe",
    'ts': "Xitsonga",
    'tt': "tatar",
    'tw': "Twi",
    'ty': "Reo Tahiti",
    'ug': "Uyghurche",
    'uk': "українська",
    'uz': "Oʻzbek",
    've': "Tshivenḓa",
    'vi': "Việt",
    'vo': "Volapük",
    'wa': "Walon",
    'cy': "Cymraeg",
    'wo': "Wolof",
    'fy': "Frysk",
    'xh': "isiXhosa",
    'yi': "ייִדיש",
    'yo': "Yorùbá",
    'za': "Saɯ cueŋƅ",
    'zu': "isiZulu",
}